generate_demo:
	./shell/processDitectDataset.sh './reasoner/ditect-fso-satisfiable.owl' './demo_files/MSI_fresh_frozen_chicken_thigh.csv' ../centralised_output
msi_query_demo:
	./shell/queryDitectKG.sh '../centralised_output/result/KG/MSI/MSI_merged_KG.owl' ../centralised_output

msi_query_local:
	./shell/queryDitectKG.local.sh '../centralised_output/result/KG/MSI/MSI_merged_KG.owl' ../centralised_output